# Generated by Django 4.1 on 2022-09-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0002_order_orderstatus_orderitem_order_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_status",
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Принят, ожидает подтверждение"),
                    (1, "В сборке у ресторана"),
                    (2, "У курьера"),
                    (3, "Выполнен"),
                ],
                db_index=True,
                default=0,
                verbose_name="Статус заказа",
            ),
        ),
    ]
