# Generated by Django 4.1 on 2022-09-25 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0003_alter_orderitem_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="name",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="surname",
            new_name="second_name",
        ),
    ]
