# Generated by Django 4.1 on 2022-09-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0003_remove_order_order_status_order_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrderStatus",
        ),
        migrations.AddField(
            model_name="order",
            name="comment",
            field=models.TextField(
                blank=True, max_length=200, null=True, verbose_name="Комментарий"
            ),
        ),
    ]
