# Generated by Django 4.1 on 2022-10-06 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0004_delete_orderstatus_order_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="called_at",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Подтвержено",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Доставлено",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="registered_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, verbose_name="Создано"
            ),
        ),
    ]
