# Generated by Django 4.1 on 2022-09-25 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0004_rename_name_order_first_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="second_name",
            new_name="last_name",
        ),
    ]
