# Generated by Django 4.1 on 2022-09-25 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0005_rename_second_name_order_last_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="first_name",
            new_name="firstname",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="last_name",
            new_name="lastname",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="phone_number",
            new_name="phonenumber",
        ),
    ]
