# Generated by Django 4.1 on 2022-10-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0005_order_called_at_order_delivered_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="called_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Подтвержено"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Доставлено"
            ),
        ),
    ]
