# Generated by Django 4.1 on 2022-09-25 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0006_rename_first_name_order_firstname_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="count",
            new_name="quantity",
        ),
    ]
