# Generated by Django 4.1 on 2022-10-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0006_alter_order_called_at_alter_order_delivered_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment",
            field=models.SmallIntegerField(
                choices=[(0, "Наличными"), (1, "Электронно")],
                db_index=True,
                default=0,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
