# Generated by Django 4.1 on 2022-10-07 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0007_order_payment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="payment",
            new_name="payment_method",
        ),
    ]
