# Generated by Django 4.1 on 2022-10-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0008_rename_payment_order_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.SmallIntegerField(
                choices=[(0, "Наличными"), (1, "Онлайн")],
                db_index=True,
                default=0,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
