# Generated by Django 3.2 on 2022-10-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0010_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.SmallIntegerField(blank=True, choices=[('cash', 'Наличными'), ('online', 'Онлайн')], db_index=True, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[('new', 'Принят, ожидает подтверждение'), ('assemble', 'В сборке у ресторана'), ('courier', 'У курьера'), ('fulfilled', 'Выполнен')], db_index=True, default='new', verbose_name='Статус заказа'),
        ),
    ]
