# Generated by Django 3.2 on 2022-10-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0011_auto_20221011_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[('new', 'Принят, ожидает подтверждение'), ('assemble', 'В сборке у ресторана'), ('courier', 'У курьера'), ('fulfilled', 'Выполнен')], db_index=True, default=0, verbose_name='Статус заказа'),
        ),
    ]
