# Generated by Django 3.2 on 2022-10-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.SmallIntegerField(blank=True, choices=[('cash', 'Наличными'), ('online', 'Онлайн')], db_index=True, default=0, verbose_name='Способ оплаты'),
        ),
    ]
