# Generated by Django 3.2 on 2022-10-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0013_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Наличными'), ('online', 'Онлайн')], db_index=True, default='cash', max_length=50, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Принят, ожидает подтверждение'), ('assemble', 'В сборке у ресторана'), ('courier', 'У курьера'), ('fulfilled', 'Выполнен')], db_index=True, default='new', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
