# Generated by Django 4.0 on 2022-11-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0017_alter_order_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Наличными'), ('online', 'Онлайн')], db_index=True, max_length=50, verbose_name='Способ оплаты'),
        ),
    ]
